# Generated by Django 4.0.6 on 2022-09-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0002_rename_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserName',
            new_name='User',
        ),
    ]
